##### Students
GET http://localhost:8080/academics/api/students
Accept: application/json
###
POST http://localhost:8080/academics/api/students
Content-Type: application/json
{
 "email": "johndoe@mail.com",
 "name": "John Doe",
 "username": "john",
 "password": "jd",
 "courseCode": 1
}
###
GET http://localhost:8080/academics/api/students/martimtsilva/subjects
Accept: application/json

###
POST http://localhost:8080/academics/api/subjects/
Content-Type: application/json

{
  "code": 555,
  "courseyear": 2030,
  "name": "Teste",
  "scholaryear": 2029,
  "courseCode": 1
}